### ISSUE TITLE
Kommentarfunktion

### ISSUE THREAD

**Issue by ChrisEis** [danielscherzer/GLSL#1]
### Installed product versions
- Visual Studio 2017 Professional
- C++ muss fürs Highlighting installierti sein
- GLSL Extension

### Description
Auskommentieren mehrerer Zeilen über `/*...*/` wird nicht korrekt in Grün dargestellt. Einige Zeilen bleiben unverändert. Beim neu laden/verändern der entsprechenden Zeilen werden diese anschließend korrekt dargestellt.
Beim Entfernen der `/*...*/` tritt die falsche Einfärbung ebenfalls auf.

**Comment by BrutPitt** [comment]
I confirm this problem, in .glsl files.
When I comment with `/*...*/` a block of code, the syntax highlight remains unchanged. 
Only if I, after, modify a single row, inside to comment block, only then the color changes to "comment color", but "only" for that row, not for entire block... and so on for the other rows inside the block.

**Comment by danielscherzer** [comment]
I can also confirm this problem, but I have no good solution for it. I use the `IClassifier` interface to implement the code classification for syntax coloring. `GetClassificationSpans` only gives me the changed parts of the code, but not the code inbetween, which is a big problem for changes that have an effect on multiple lines (like the ``/*...*/`` comments may have. I can detect when an ``/*`` or ``*/`` is typed, but I do not know how to say to Visual Studio to invalidate the liens of code inbetween. If you have any knowledge about that I would be happy to implement it.

**Comment by danielscherzer** [comment]
My tests indicate that this issue should be resolve by the commit mentioned above. I will close the issue. Please reopen if the problem persists!

**Comment by BrutPitt** [comment]
Thank you very much.
Now is perfect!
(tested on VS2019 16.5.3)
