### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Ryngetsu** [danielscherzer/GLSL#10]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: The latest version

I'm kinda new to Visual Studio and OpenGL but how do I use this? I've installed it but nothing changes. My files extension are .vs and .fs. Maybe that's the problem? Can I change the file's language without changing the extension?

Thank you

**Comment by danielscherzer** [comment]
Hi! The default file extensions used by this extension do not include yours, but I just posted an update were you can configure your own file extensions. Cheers!

**Comment by Ryngetsu** [comment]
Well thank you very much I'll try it

**Comment by Ryngetsu** [comment]
Works amazing man!!

Haven't tested much but only seen one very little problem. When writing the opening bracket and hitting enter, there isn't automatic indentation.

Thank you for your work.

**Comment by danielscherzer** [comment]
Thanks!
