### ISSUE TITLE
gl_LaunchSizeEXT keyword is not detected, yet gl_LaunchSizeEX is

### ISSUE THREAD

**Issue by DrNoodles** [danielscherzer/GLSL#104]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: 0.11.159

### Description
gl_LaunchSizeEXT keyword is not detected, yet gl_LaunchSizeEX incorrectly is.
gl_LaunchSizeEX  is not a keyword.

### Current behavior
gl_LaunchSizeEX is being highlighted as a keyword (wrong) 

### Expected behavior
gl_LaunchSizeEXT should be highlighted as a keyword

**Comment by danielscherzer** [comment]
Does it work now?
