### ISSUE TITLE
No highlighting for .frag and .vert in VS2022

### ISSUE THREAD

**Issue by nuked44** [danielscherzer/GLSL#111]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: 0.11.160

### Description
There is no highlighting for .frag and .vert files

### Steps to recreate
1. Install VS2022 Community
2. Install the extension

### Current behavior
No highlighting for .frag and .vert  

### Expected behavior
Highlighting for .frag and .vert files

**Comment by TheEndHunter** [comment]
A work around so you can still use highlighting is to try using .glsl as the file extension for now, the issue is most likely cause by another extension(or the HLSL highlighting) getting priority on the file extension.

**Comment by danielscherzer** [comment]
Exactly
