### ISSUE TITLE
No multi-line comment collapse.

### ISSUE THREAD

**Issue by Pharos1** [danielscherzer/GLSL#113]
### Installed product versions
- Visual Studio: [2022 Community]
- This extension: [0.11.164]

### Description
Collapse not available for comments. I tried different projects and searched for comment collapse in Tools->Options, but it didn't work, I think the problem is with the extension.
It actually worked when the file extension was .hlsl, but it didn't work for some other extensions(I tried .glsl, .frag, .vert and .mesh, all of them had the bug).

![Untitled](https://user-images.githubusercontent.com/114859787/232887677-e67306e3-ebbe-4c93-8c69-3bb2c55f93da.png)

### Steps to recreate
1.Well, just make a C++ project.
2.Create a file with file extension .frag, .glsl or .vert
3.Make a multi-line comment and see that it cannot collapse.

### Current behavior
I explained it in the description.

### Expected behavior
It should be able to collapse multi-line comments like it used to do.

### Edit
It was working before, which might not be obvious from the things written above.

**Comment by danielscherzer** [comment]
Hi! Thanks for using my extension! I just had a look into the code and I never implemented collapse for comments, but only for code blocks because of some issues with multi-line comments vs. multiple lines of comments.... Also code block collapse has some bugs, so I never extended it further.

Could it be that you had nsight installed before, which provides this feature?

**Comment by Pharos1** [comment]
> Hi! Thanks for using my extension! I just had a look into the code and I never implemented collapse for comments, but only for code blocks because of some issues with multi-line comments vs. multiple lines of comments.... Also code block collapse has some bugs, so I never extended it further.
> 
> Could it be that you had nsight installed before, which provides this feature?

Sorry for replying late, but I have never installed nsight and it was working before. I was able to collapse comments but I don't know why I was able to do so when you have never implemented it. Sorry for losing your time then, have a great day!
