### ISSUE TITLE
UnrealVS extension is not working when glsl language integration is enabled (for non-unreal projects)

### ISSUE THREAD

**Issue by v310r** [danielscherzer/GLSL#114]
### Installed product versions
- Visual Studio:  2022 Community
- This extension: 0.11.160
- UnrealVS version: 1.72

### Description
getting an error on solution startup, that UnrealVS did not load correctly
![image](https://github.com/danielscherzer/GLSL/assets/80487632/5b0dafa7-cb9a-4a82-8c04-af016d92b058)

### Steps to recreate
1. Download and enable the UnrealVS extension
2. Download and enable glsl extension
3. open any non-unreal solution

### Current behavior
currently, UnrealVS cannot be used, but when I tried to disable glsl extension - it began to work.

I checked ActivityLog.xml and found such a string:

<entry>
    <record>457</record>
    <time>2023/06/16 21:09:05.508</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [UnrealVSPackage]</description>
    <guid>{DDBF523F-7EB6-4887-BD51-85A714FF87EB}</guid>
  </entry>
  <entry>
    <record>458</record>
    <time>2023/06/16 21:09:05.904</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [UnrealVSPackage]Source: &apos;&apos; Description: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.GetOutputPane(Guid page, String caption)&#x000D;&#x000A;   at UnrealVS.UnrealVSPackage.GetP4OutputPane()&#x000D;&#x000A;   at UnrealVS.P4Commands..ctor()&#x000D;&#x000A;   at UnrealVS.UnrealVSPackage.&lt;InitializeAsync&gt;d__86.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{DDBF523F-7EB6-4887-BD51-85A714FF87EB}</guid>
    <hr>0x8000ffff - E_UNEXPECTED</hr>
    <errorinfo></errorinfo>
  </entry>

### Expected behavior
UnrealVS and glsl should work independently and correctly without any errors for non-unreal projects

**Comment by danielscherzer** [comment]
Thanks for reporting the problem. I found two Unreal extensions on the marketplace: I assume the problem is with [this extension](https://marketplace.visualstudio.com/items?itemName=Fiquegnima-productions.UnrealExntension)? Did you try the [unreal wizard](https://marketplace.visualstudio.com/items?itemName=Fiquegnima-productions.UnrealWiz)?
