### ISSUE TITLE
Feature request: turn off errors and warnings?

### ISSUE THREAD

**Issue by rxght** [danielscherzer/GLSL#115]
### Installed product versions
- Visual Studio 2019 Community
- This extension: 0.11.160

### Description
Maybe it's possible to add an option to turn off errors and warnings. I'm getting an error when using Vulkan-specific global variables. I'm being told to use `#extension GL_KHR_vulkan_glsl : enable` but when I add it to the file I get a warning from my compiler instead. Preferable would be to just turn off errors and warnings as I'm only after the syntax highlighting anyways.

**Comment by pernicius** [comment]
if you only use the highlighting (like me), add the following to your shader:

//! #extension GL_KHR_vulkan_glsl : enable

it will be ignored by glslc

**Comment by danielscherzer** [comment]
Hi, thanks for using my extension.
This option exists (live compiling on/off) in Tools -> Options -> glsl
For Vulkan people use the external compiler glslang ([see readme on github)](https://github.com/danielscherzer/GLSL#external-compiler)
