### ISSUE TITLE
I can't use this extension in VS2022

### ISSUE THREAD

**Issue by yehu1999** [danielscherzer/GLSL#117]
### Installed product versions
- Visual Studio: 2022 Community
- This extension:0.11.166

### Description
I couldn't open every file(.cpp/.h/.c/.myfiles) if I use this extension.

### Steps to recreate
1. install this extension
2. restart the VS 
3. open a projection
4. couldn't use

### Current behavior
When open a file, it says "No EditorOptionDefinition export found for the given option name".
I want to fix it by the way in https://stackoverflow.com/questions/23893497/no-editoroptiondefinition-export-found-error
and I try to reboot，
but they didn't work both.
if I close this extension,everything comes to normal.
so I think the problem maybe from the extension.

### Expected behavior
I want to use it without ERROR.

**Comment by danielscherzer** [comment]
Unfortunately Visual Studio 2022 + my extension seem to work only in some versions and not in other versions. Often the problem goes away with the next release of VS. I did not find out why. Hopefully the next version of VS removes the problem for you.

**Comment by pitaohc** [comment]
I have the same problem in VS 2022 (v17.6.2). The version of this extension is 0.11.166.
When I open a solution in VS. It will occur an error shown in following picture.
![QQ截图20230923112826](https://github.com/danielscherzer/GLSL/assets/36119151/310d2e41-8a33-4b53-b4d5-640df67af1b0)
It means VS can't load "EditorPackage" successfully. The problem may be occurred by profile changed or an extension installed.
Furthermore, another problem is shown when I tried to open any source code files.
![QQ截图20230923112844](https://github.com/danielscherzer/GLSL/assets/36119151/6c6eb00e-8678-41df-ab8d-149233cc3983)
I tried to close all extensions but glsl to address problems. These problems will appear only when glsl extension is enabled.
I hope this information is helpful for you.

**Comment by Guglis02** [comment]
Same problem here, using VS 2022 v17.6.5 on Windows 11.

![image](https://github.com/danielscherzer/GLSL/assets/37349209/a2feac1a-3095-40d0-8b0c-30693c7bb8d5)

**Comment by danielscherzer** [comment]
THe new version may resolve this issue. Please try it out.

**Comment by danielscherzer** [comment]
Possibly related issue #112

**Comment by canyon-online** [comment]
Had this issue on VS2022 17.5.x but updating to 17.7.5 fixed it 🙂

**Comment by yehu1999** [comment]
> 在VS2022 17.5.x上遇到此问题，但更新到17.7.5修复了此问题 🙂

YEAH！

**Comment by danielscherzer** [comment]
Any remaining problems with VS 2022?

**Comment by woshiZS** [comment]
> Any remaining problems with VS 2022?

My previous VS version 17.3.x and I met the same problem，by upgrading VS, the problem disappeared and  all works fine🙂!

**Comment by yehu1999** [comment]
> Any remaining problems with VS 2022?

Everything is all right！Great tool，very useful，thanks for fixing it!

**Comment by llibetter** [comment]
![image](https://github.com/danielscherzer/GLSL/assets/44372726/6e56f5e9-fca4-461b-a385-61a6e3ddf991)

I have same problem with vs 2022 17.8.7,update to 17.9.6, it works fine

**Comment by a237787115** [comment]
Good
