### ISSUE TITLE
Undeclared identifier gl_Position

### ISSUE THREAD

**Issue by RunDevelopment** [danielscherzer/GLSL#12]
### Installed product versions

- Visual Studio: 2017 Professional
- This extension: 0.2.36
- OS: Windows 10 Pro 64bit

### Description

When assigning a vector to `gl_Position`, I always get the two errors:

```
'gl_Position': undeclared identifier
'assign': cannot convert from '4-component vector of highp float' to 'highp float'
```

The compiler seems to not know `gl_Position`, but curiously it also thinks that it's a float.

### Steps to recreate

1. Use any vertex shader. E.g.:
```glsl
#version 330 core

in vec3 v_position;

void main() 
{
    gl_Position = vec4(v_position, 1);
}
```

### Current behavior

The errors from above are displayed.

### Expected behavior

It should not display any errors.

**Comment by RunDevelopment** [comment]
A few people I know also have this problem. We all use laptops with an integrated Intel graphics card and an additional Nvidia GPU.
I don't know which compiler it will pick, but when I ran the code, it worked for both GPUs.

**Comment by danielscherzer** [comment]
I was not able to reproduce this error. The extension picks the default gaphics card set in the NVIDIA control panel, so you can force the extension to choos the NVIDIA be seting it in the control panel and restarting visual studio.

**Comment by RunDevelopment** [comment]
When forcing VS to use the NVIDIA card, I get:
```
error C5052: gl_Position is not accessible in this profile
```

Switching back to the integrated Intel will result in the same error as in first the comment.

**Comment by danielscherzer** [comment]
This means that the shader is compiled with the wrong profile (not vertex, but fragment or other shader type). What is the extension of your vertex shader? Is this extension registered as a vertex shader extension in the options menu?

**Comment by RunDevelopment** [comment]
Yep, you're right.
`.glsl` files, which I use for all kinds of shaders, are detected as fragment shaders by default.

It'd be nice if file name was used to guess the correct shader type when using the file extension as non-descriptive as `.glsl`. E.g. all my vertex shader files end with `_vertex.glsl`.

**Comment by RunDevelopment** [comment]
Maybe as an alternative, we could add an option to manually set the shader type of a file (maybe via as context menu entry like 'Set shader type' with all different shader types and an auto-detect option as sub entries).
The file name plus shader type could then be stored somewhere, so I don't have the set the shader type for each file every time I open them.

**Comment by danielscherzer** [comment]
If I understand correctly, this per filename setting would take precedence over the per file extension setting. Only downside I currently can see is that it becomes tedious if you have hundreds of shaders, which need to be set this way, but who does.... So if you want I'm happy if you could implement this feature.

**Comment by RunDevelopment** [comment]
Yes, the per file settings will overwrite the file extension's ones. But it is also only a quick fix for false detection and does not replace good shader type detection. I also think that the file extension approach is generally the best one, but it fails in the case of a more general file extension (like `.glsl`). So why don't we do this.

We move the `.glsl` extension into a new auto-detect category, in which we will try to guess the shader type using hints in the file name and shader specific variable like `gl_Position`, `gl_FragDepth`, etc. (Let's just hope the people don't use the preprocessor the change the type of the shader)
The new category also means that the context menu will have another option. Beside the different shader type, it will also have the file extension based approach (default) and the auto-detect approach (default for `.glsl` files).

I will try to implement it, but it will take a while.

**Comment by danielscherzer** [comment]
Another idea that could help with this kind of problem would be to add a line in the shader source code that states the shader type like `// vertex shader`, which again would take precedence over the file extension mechanisme. i think i could implement this version very quickly because i parse parts of the source code anyway. would this be a useful solution to your problem?

**Comment by RunDevelopment** [comment]
Sorry, I haven't noticed your comment.

Yes this will also solve my problem.

**Comment by danielscherzer** [comment]
Version 0.4 includes a simple auto detect shader type for *glsl. 
please feel free to try it out.
