### ISSUE TITLE
Stable Version?

### ISSUE THREAD

**Issue by DmitriyBatkovich** [danielscherzer/GLSL#126]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: lasted version on github

### Description
It throws a bunch of errors when starting VS 2022

### Steps to recreate
1.Download the latest version from GitHub
2.Install the VSIX file
3.Enjoying a bunch of bugs in VS 2022

So the question is which version is currently stable for VS 2022?

**Comment by DmitriyBatkovich** [comment]
Do you have this problem?

**Comment by DmitriyBatkovich** [comment]
So I updated Visual Studio 2022 to the latest version and installed the extension version: [0.11.171](https://github.com/danielscherzer/GLSL/releases/tag/0.11.171)
Everything is working now thanks

**Comment by danielscherzer** [comment]
> Do you have this problem?

No. The extension version 0.11.173 works for me.
