### ISSUE TITLE
Errors are not marked (no squiggle-underline)

### ISSUE THREAD

**Issue by MV10** [danielscherzer/GLSL#127]
VS 2022 v17.9.6
Extension v0.11.170

I'm not sure exactly when this broke, but some time last year the plugin stopped marking _most_ error lines with the red squiggle. I just updated to the version shown above today and the problem persists, and I think this is the second time I've updated since it showed up. The editor "Show error squiggles" option has not been disabled and it works in other languages. I don't know if it's related, but as I'm actively typing it shows the red squiggle, but it goes away when I stop (I assume after the 200ms compiler delay). I can't recall if it did that back when the error squiggles worked correctly.

I say "most" errors because sometimes (very rarely) it does work. For example, I added the garbage "asdf" to this line and clicked elsewhere which dismissed the intellisense popup:

![image](https://github.com/danielscherzer/GLSL/assets/794270/d6356602-344c-4e3a-b92b-3db7c9d67c81)

But then I go right back to that same line and replace "asdf" with "querty" and before I even leave the line or dismiss intellisense, the squiggle goes away:

![image](https://github.com/danielscherzer/GLSL/assets/794270/b657f23c-36fe-4ccb-a2fc-345801e6487a)

However, it still _recognizes_ the error exists; if I hover the mouse pointer over the line, it'll pop up the correct error message:

![image](https://github.com/danielscherzer/GLSL/assets/794270/3f41c490-7774-4b33-be32-c5872f0003ba)

**Comment by danielscherzer** [comment]
Thanks for your feedback! I do not get the missing squiggles. Are you using an external compiler?

**Comment by danielscherzer** [comment]
Hm, not sure why it's not working...

**Comment by MV10** [comment]
Yeah the problem persisted even through a complete uninstall and reinstall of VS. I had reported a MAUI Android bug to them and they asked me to remove VS and try a preview version. I think that was back around December. Then I went back to the release version and reinstalled this and a few other extensions I use.

About the only thing I really disable with any wide impact is CodeLens, but re-enabling that had no effect (and I wouldn't expect it to).

**Comment by danielscherzer** [comment]
The new version works for me now. Hopefully for you too.

**Comment by MV10** [comment]
YES! Working now.

Wow, every few days I spend a few hours writing GLSL, this is fantastic. Thank you!

**Comment by danielscherzer** [comment]
Thanks!
