### ISSUE TITLE
Release 0.11.174 and 0.11.173 completely break visual studio

### ISSUE THREAD

**Issue by Amani747** [danielscherzer/GLSL#129]
### Installed product versions
- Visual Studio: 2022
- This extension: 0.11.174 and 0.11.173 ( earlier versions work )

### Description
With either of those two versions installed when a project is opened, the editor first displays:

![Error01](https://github.com/danielscherzer/GLSL/assets/14146503/af7ad57a-dde1-42c4-a397-d3c3001ed517)

When a editor tab is selected for a project file of any file type the following is displayed instead:

![Error02_00](https://github.com/danielscherzer/GLSL/assets/14146503/228a2d93-78a3-48c4-9a85-d3f83a210fe5)
![Error02_01](https://github.com/danielscherzer/GLSL/assets/14146503/b13cbc57-b381-4dc5-89bb-fe1d5a9809e7)

### Steps to recreate
1a. Upgrade from 0.11.172 to either 0.11.174 or 0.11.173
1b. Install a fresh copy of either 0.11.174 or 0.11.173

**Comment by danielscherzer** [comment]
Thanks for your feedback! What is the exact version of your Visual Studio Installation?
The extension is working for me and my version is 17.9.6.

**Comment by Amani747** [comment]
> Thanks for your feedback! What is the exact version of your Visual Studio Installation? The extension is working for me and my version is 17.9.6.

My visual studio version is Version 17.8.7 - let me update.

**Comment by Amani747** [comment]
> Thanks for your feedback! What is the exact version of your Visual Studio Installation? The extension is working for me and my version is 17.9.6.

Updating to version 17.9.6 has completely resolved the issue. Thanks!

That's silly of me, somewhere along the line I've ignored or turned off updates.
