### ISSUE TITLE
GLSL extension has no effect

### ISSUE THREAD

**Issue by Nanami-Scarlet** [danielscherzer/GLSL#130]
### Installed product versions
- Visual Studio 2022 Community  version 17.12.3
- This extension: 0.11.174

### Description
no highlight, no code completion.

please look the following pic  
![image](https://github.com/user-attachments/assets/34196073-224c-49fe-adb1-f02cc42da160)

Thank you very much for being able to solve this problem.    :)

**Comment by Nanami-Scarlet** [comment]
this file's extension name is .glsl.
And I try to install and uninstall the GLSL extension many times. I have no idea to deal with it.

**Comment by danielscherzer** [comment]
What other extensions do you have installed?

**Comment by Nanami-Scarlet** [comment]
> What other extensions do you have installed?

![image](https://github.com/user-attachments/assets/d0aed380-b10f-4abf-a2e3-dae08e6588ac)
that's all extensions I have installed.

**Comment by danielscherzer** [comment]
I guess that one of the other shader related extensions has already ownership of .glsl files. You could try to setup a custom file extension in my extension for debugging purposes.

**Comment by Nanami-Scarlet** [comment]
> I guess that one of the other shader related extensions has already ownership of .glsl files. You could try to setup a custom file extension in my extension for debugging purposes. Our you could try disabling other extensions to look which interferes...

I just created a file named "test.test" and restarted Visual Studio it works.  :)
next I will find what extension to causes it.

cheers!

**Comment by danielscherzer** [comment]
Excellent! Happy to help!
