### ISSUE TITLE
Format using clang-format

### ISSUE THREAD

**Issue by wumo** [danielscherzer/GLSL#24]
### Installed product versions
- Visual Studio: [2017 Professional]
- This extension: [0.4.53]

### Description
Add support for formatting shader files using clang-format

### Current behavior
Currently no format support

### Expected behavior
Require user to install clang-format.exe  and configure the path in `GLSL language integration`.
Then we can format the shader files using clang-format.exe.

**Comment by danielscherzer** [comment]
I'm not sure I understand the suggested improvement. As I understand you want to be able to use a certain formating syntax (clang-format) to specify how shader files should be formated. Is this not covered by the https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.ClangFormat vs extension?

**Comment by wumo** [comment]
vs 2017 has built-in support for clang-format, but it doesn't recognize glsl files.

**Comment by wumo** [comment]
Ok, I know. It seems that the vs 2017 built-in clang-format doesn't recognize glsl, but `ClangFormat ` extensions can be applied on every file.
