### ISSUE TITLE
Extension  crashed when vs2017 start without project

### ISSUE THREAD

**Issue by Kylewlk** [danielscherzer/GLSL#25]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 0.4.54

### Description
Extension  crashed when vs2017 start without project.

### Steps to recreate
1. Install GLSL language integration
2. Install [Productivity Power Tools 2017/2019](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017)
3. Start vs2017 without project

### Current behavior
Vs2017 will pop up  following dialog box,

![20181120144655](https://user-images.githubusercontent.com/22131472/48757829-fdcd9580-ecd8-11e8-9a83-203645e04bf1.png)
![20181120144704](https://user-images.githubusercontent.com/22131472/48757832-002fef80-ecd9-11e8-93e4-648d188fdd8a.png)

This is the ActivityLog.xml: [ActivityLog.zip](https://github.com/danielscherzer/GLSL/files/2598577/ActivityLog.zip)

The following text is line 860 in AcitvityLog.xml 

A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part &quot;DMS.GLSL.Classification.FileExtensionsOption&quot;. ---&gt; System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.PackageContainer.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Container.Site.GetService(Type service)&#x000D;&#x000A;   at System.ComponentModel.Component.GetService(Type service)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.get_SettingsManager()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.DialogPage.set_Site(ISite value)&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component, String name)&#x000D;&#x000A;   at System.ComponentModel.Container.Add(IComponent component)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)&#x000D;&#x000A;   at DMS.GLSL.Classification.OptionsPagePackage.EnsurePackageLoaded() in C:\projects\glsl\src\Classification\OptionsPagePackage.cs:line 59&#x000D;&#x000A;   at DMS.GLSL.Classification.OptionsPagePackage.get_Options() in C:\projects\glsl\src\Classification\OptionsPagePackage.cs:line 40&#x000D;&#x000A;   at DMS.GLSL.Classification.FileExtensionsOption..ctor(IContentTypeRegistryService contentTypeRegistry, IFileExtensionRegistryService fileExtensionRegistry) in C:\projects\glsl\src\Classification\FileExtensionsOption.cs:line 14&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()

**Comment by danielscherzer** [comment]
As a first test I can confirm that also after first installing my extension and afterward installing the  Productivity Power Tools 2017/2019 I got this exception/message.

**Comment by danielscherzer** [comment]
I published a new version. The two extensions now work for me without exception. Does it work for you too?

**Comment by Kylewlk** [comment]
Yes, it works well.
