### ISSUE TITLE
Recent GLSL Versions (> 430) Not Recognized

### ISSUE THREAD

**Issue by Lotharyx** [danielscherzer/GLSL#26]
### Installed product versions
- Visual Studio: 2017 Professional 15.8.2
- This extension: 0.4.55

### Description
#version declarations more recent than 430 are unrecognized, generating a red squiggle and "(error #106) invalid shader version number"

### Steps to recreate
1. Create a new text file in a solution, giving it one of the GLSL-recognized extensions, e.g. shader.frag
2. Enter a version declaration newer than 430 (e.g. 450, ratified May 2017)
3. Observe squiggle

### Current behavior
Versions newer than 430 are flagged as errors, although GLSL versions 440, 450, and 460 are in public release.

### Expected behavior
Versions newer than 430 should not be flagged as an error.

**Comment by Lotharyx** [comment]
Oh, yes that’s very possible.  My dev platform is a few years old.  Thanks for clearing that up!  

>

**Comment by danielscherzer** [comment]
I have included the option to use an external compiler, like glslangValidator, so you can run edit "new" shader code on old hardware. Cheers!
