### ISSUE TITLE
Custom colors for new or redefined funcs

### ISSUE THREAD

**Issue by barnes14** [danielscherzer/GLSL#28]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 0.5.63

### Description
how to set the color for texture2DRect or any redefined funcs? 
Like 
#define texLod textureLod

**Comment by danielscherzer** [comment]
Currently you can't. The extension does not parse the code to understand what is a macro or a function, but has fixed lists for the reserved names of glsl, grouped into variables, functions and keywords. For these 3 groups you can change the color in the visual studio option menu under Environment -> Fonts and Colors -> Display Items with GLSL as prefix. Does this help you?

**Comment by barnes14** [comment]
I know how to change colors) About lists - can I change them?

**Comment by danielscherzer** [comment]
Currently only during compile-time. The list with reserved names are compiled with the extension code as resources.

**Comment by barnes14** [comment]
I thought as much) Can you tell me where in the code I can add my extensions?

**Comment by danielscherzer** [comment]
That depends on what exactly do you want as a result: Should macros be detected and colored if the substitute a function or do want to add a user defined list of names that will be colored or something else?

**Comment by barnes14** [comment]
I think a custom list of extensions will be enough

**Comment by danielscherzer** [comment]
The new release includes a user key words option field. You can enter a space separated list of key words. These will be colored with the GLSL user key word color under the Fonts and Colors section.

**Comment by barnes14** [comment]
Nice!!! Big tnx))

**Comment by danielscherzer** [comment]
Glad to help!
