### ISSUE TITLE
No autocompletion in shader files

### ISSUE THREAD

**Issue by LucasAstro** [danielscherzer/GLSL#30]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 0.5.67

### Description
No code completion

### Steps to recreate
I'm not sure if it's just my VS messing up or reproducible but this is my setup:
I have this GLSL code
```GLSL
#version 330 core 
out vec4 FragColor;
void main()
{
	FragColor = vec4(1.f, 0.f, 0.f, 1.f);
}
```
In a file "shader.vert" and intellisense is on

### Current behavior
No autocompletion in shader files

### Expected behavior
Have autocompletion working (Sorry if not descriptive enough or badly written, I don't make issues often.)

**Comment by LucasAstro** [comment]
Oh I'm so sorry, it appears that was the case. Apologies. I will close it now!

**Comment by danielscherzer** [comment]
Thanks!
