### ISSUE TITLE
Missing subgroup key words

### ISSUE THREAD

**Issue by Carandiru0** [danielscherzer/GLSL#31]
### Installed product versions
- Visual Studio: 2017
- Latest extension version

### Description
Missing highlight support for subgroups. Vulkan subgroups are the wave / intrinsic gpu functionality now supported in Vulkan 1.1
glslangvalidator has support for compiling with the official (latest) vulkan sdk.

**Comment by danielscherzer** [comment]
I just look at the GL_KHR_shader_subgroup and there are tons of new identifiers all around the place. Could you give me a list of the new identifiers (space separated) then it would be easy for me to include them in my extensions?
