### ISSUE TITLE
Error in installation of Extension

### ISSUE THREAD

**Issue by Sid911** [danielscherzer/GLSL#34]
### Installed product versions
- Visual Studio: 2019 community edition
- This extension: 0.5.67 Version from VS MarketPlace

### Description
Error in installation of the extension

### Steps to recreate
1. Install the extension from Marketplace
2. Restart the visual studio for further installation 
3. Error in installation ¯\_(ツ)_/¯

### Current behavior
There are a few problems during installation which is repetitive. Means it doesn't go away after many trials of installation of the extension 😅 

### Expected behavior
Of course, it should install correctly in a seamless manner 😎 . I have linked log file and a screenshot of the error below 
### Resources
[dd_VSIXInstaller_20190708231330.log](https://github.com/danielscherzer/GLSL/files/3369624/dd_VSIXInstaller_20190708231330.log)

![image](https://user-images.githubusercontent.com/27860105/60831490-55246580-a1d7-11e9-8e43-9c265a1113ff.png)

**Comment by danielscherzer** [comment]
I must confess, I have no idea were this error comes from. Regrettably I cannot replicate it on my installation (Visual Studio 2017 Enterprise), but I know of users who use Visual Studio: 2019 community edition succesfully. I googled the errors in the log file and did not come up with anything usefull.

**Comment by Sid911** [comment]
Thanks but I don't know somehow it started working after updating visual studio.. I think I should close this issue now 😀
