### ISSUE TITLE
Adding support for GLSL_NV_ray_tracing non-trivial ?

### ISSUE THREAD

**Issue by JamesAMD** [danielscherzer/GLSL#36]
### Installed product versions
- Visual Studio: [VS 2017 Community]
- This extension: [0.5.64]

### Description
I've been using this extension for writing GLSL shaders for use with Vulkan, and it's been an immense help.
Recently however, I started experimenting with NVIDIA's ray tracing  extension, VK_NV_ray_tracing.
It introduces a set of new shader stages, one of which is the raygen (ray generation) shader.

Out of the box, even this extension directive results in a squiggly error marker:
`#extension GL_NV_ray_tracing : require`
This is resolved by setting the latest `glslangValidator.exe` executable as the external compiler.

However, when I try to use the storage qualifier `rayPayloadNV` like so:
`layout(location=0) rayPayloadNV vec3 ray_payload;`
this again results in an error marker saying:  `'rayPayloadNV' : not supported in this stage: fragment`

So, the raygen shader file is clearly treated as a fragment shader when being compiled for error detection.

I took a quick look at the source code, and the extension's shader compilation apparently relies on `Zenseless.HLGL`, which in turn relies on `OpenTK` (which I know nothing about).
Based on this (quick) observation, it seems it would be a quite a lot of work to support the shader stages added in `GLSL_NV_ray_tracing`, and the constructs supported by it.

Could you share your thoughts on this matter ?

### Steps to recreate
1. Set the latest `glslangValidator.exe` executable as the external compiler.
2. Write a raygen shader file `test.rgen` like so:
```
#version 460
#extension GL_KHR_vulkan_glsl : enable
#extension GL_ARB_separate_shader_objects : enable
#extension GL_NV_ray_tracing : require

layout(set=0, binding=0) uniform accelerationStructureNV u_tlas;
layout(set=0, binding=1, rgba8) uniform image2D u_result;

layout(location=0) rayPayloadNV vec3 ray_payload;

void main() {
  
}
```
3. Observe the squiggly red error marker under the line 
`layout(location=0) rayPayloadNV vec3 ray_payload;`,
with the error message:
`'rayPayloadNV' : not supported in this stage: fragment`

### Current behavior
No support for shader stages and constructs added in GLSL_NV_ray_tracing.

### Expected behavior
Hopefully, GLSL_NV_ray_tracing would be supported.

**Comment by danielscherzer** [comment]
I think it should work now. Because OpenTK currently only supports the "core" shader types, you still have to use an external compiler for now.

**Comment by JamesAMD** [comment]
Thank you !

I just installed the latest version,  set the latest `glslangValidator.exe` as the external compiler, `-V` as an argument for it, 
and confirmed it to be working with my `raygen`, `closest hit`, and `miss` shaders, with all the new keywords and built-in variables !

Addition of support for `mesh` and `task` shader stages is nice as well 😄  !

Honestly I didn't expect the support to be added so fast, this is incredible !

I think this issue could be closed, if you have no problem.
Again, thanks so much. 😃

**Comment by danielscherzer** [comment]
I'm happy to help. Thanks for your feedback!
