### ISSUE TITLE
Some information output by glslangValidator has no line number

### ISSUE THREAD

**Issue by wxyu247** [danielscherzer/GLSL#38]
#version 330 es
output:
ERROR: #version: only version 300, 310, and 320 support the es profile
ERROR: 1 compilation errors.  No code generated.

vs will not prompt an error, can print error message to the output window

**Comment by danielscherzer** [comment]
hallo,
is the issue that the line numbers are missing in the error output of the extension?
The faulty input `#version 330 es` in a shader file when run through glslangValidator creates the output you wrote above. Without any line numbers in the error statements. So when I parse the error output I cannot print any line numbers in my error message in Visual Studio and hence there also are no squiggly lines. In my opinion glslangValidator breakes his usual error output syntax in this case. What do you think?

**Comment by wxyu247** [comment]
Compiling with graphics cards also has some cases where there are no line numbers, such as typing characters at the end of the file, not following spaces or line breaks.
Maybe the graphics card is different, the situation will be different.

void main()
{
}text

**Comment by wxyu247** [comment]
Print an error message to the output window. Considering that these errors are rare, you can add an option to choose whether to print.
I am going to modify the code.
