### ISSUE TITLE
Installer doesn't load

### ISSUE THREAD

**Issue by JayDee-github** [danielscherzer/GLSL#41]
### Installed product versions
- Visual Studio: [example 2017 Professional]
- Latest as of 10/18/19
### Description
Not sure why, but the installer didn't finish and now does nothing when I try to load it.

### Steps to recreate
1. Load extension installer

### Current behavior
Installer doesn't load.  VS 2017 tells me to reinstall

**Comment by danielscherzer** [comment]
Interesting. Let's see if other people have the same problem. It did of course work for me. Did you do a uninstall/install cycle for the extension?

**Comment by danielscherzer** [comment]
Does the new version 0.7.80 resolve this issue?

**Comment by danielscherzer** [comment]
I will close this issue because a number of new versions have been released. Please reopen if the porlbem still persists.
