### ISSUE TITLE
Text unreadable in VS Light theme

### ISSUE THREAD

**Issue by YaakovDavis** [danielscherzer/GLSL#42]
With the VS light theme, variable names appear too bright (notice the `gl_Position` variable):

![image](https://user-images.githubusercontent.com/965750/67378287-b6f2ba80-f58f-11e9-8ecb-fc82601c69ae.png)

**Comment by danielscherzer** [comment]
The colors are customizable via the options dialog of Visual Studio.

**Comment by YaakovDavis** [comment]
Found it, thanks.  
For anyone interested, it's under Environment  > Fonts and Colors > GLSL variable.
