### ISSUE TITLE
Could not find the Microsoft.VisualC.CppClassifierProvider. Installing the C++ Visual Studio aspect should help.

### ISSUE THREAD

**Issue by Yen** [danielscherzer/GLSL#43]
### Installed product versions
- Visual Studio: 2019 Professional 16.4.0 Preview 4.0
- This extension: 0.6.78

### Description
Error message doing almost anything
"Could not find the Microsoft.VisualC.CppClassifierProvider. Installing the C++ Visual Studio aspect should help."

### Steps to recreate
1. Try and do most things (opening and viewing files)
2. Message box with error

I believe this is related to [this issue](https://developercommunity.visualstudio.com/content/problem/807751/could-not-find-the-microsoftvisualccppclassifierpr.html) but not sure if this is a bug on their end or an API change required on yours.

**Comment by danielscherzer** [comment]
I assume you have installed the C++ aspect and it still does not work?

**Comment by Yen** [comment]
Believe it or not, the C++ aspect _is_ installed. I didn't change any of the VS components before or after upgrading so I expect them to be the same, but if you know what specific C++ aspect may be missing then: 
![image](https://user-images.githubusercontent.com/10085851/68580343-1563d800-046e-11ea-8668-2ca9ddcd1fc0.png)

I have done a full repair of the install to no avail. :(

**Comment by danielscherzer** [comment]
I can only guess what VS 2019 needs (I still use 2017), but on my Visual Studio I have installed the VC++ 2017 version 15.9 tools in the Compiler, Buildtools and runtime category and the Visual Studio C++ core features in the development activities category. I'm unsure if those are the required components and if the have the same naming in VS 2019, but these are the only C++ specific modules I have installed. Sorry! 
Despite this the extension installer should normally install all required dependencies automatically. In your case this seems not to be the case. The issue you posted in your first post sounds to me related. So if everything else fails I would recommend to sit it out till the next update for 2019 is out. 

Cheers,
Daniel

**Comment by jasonb01** [comment]
CppClassifierProvider was an internal class that was recently deleted (renamed and then changed to a different type).  Please don't use our internal undocumented functions.

**Comment by danielscherzer** [comment]
@jasonb01 thanks for the insider information! What is the recommended way of using a C++ syntax classifier? I was using it to do the heavy lifting of parsing all the C alike elements in glsl code.

**Comment by jasonb01** [comment]
I'm sorry but there is no public API provided by VS available for this.  What this code is doing by instantiating this on its own is confusing our language service and probably causing VS instability and memory leaks because our syntax classifier and our language service are tightly bound and not meant to be used as standalone components for arbitrary usage.

Unfortunately the recommendation is to roll your own lexer or use some other open source lexer and use it to power your own classifier.  Another benefit of that will be that you will now have tight control over what your results are for the specific C dialect in question instead of our classifier that must work on all C dialects and probably produce extraneous results in your case of GLSL.

**Comment by danielscherzer** [comment]
Ok thanks. This will take a while to implement.

**Comment by PcChip** [comment]
well that's no good  
I'll uninstall it to stop getting the error messages, and wish you the best of luck figuring out a workaround to that :\

**Comment by danielscherzer** [comment]
I implemented parsing with Sprache. Hopefully the extension works again. Please let me know! 
Cheers, Daniel

**Comment by Yen** [comment]
Looks good to me, thanks!

**Comment by dbechrd** [comment]
@danielscherzer Thank you sooo much for fixing this! This extension is extremely useful but the modal popup spam caused by this error were disastrous and forced me to uninstall it. Great to be able to use it again. <3
