### ISSUE TITLE
VS 2019 with C# solution cause VS crash

### ISSUE THREAD

**Issue by lancelot-coder-chen** [danielscherzer/GLSL#44]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 0.6.78

### Description
When open a C# solution in VS 2019 (16.3.8 and 16.3.9), this extension cause VS crash.

### Steps to recreate
1. using VS 2019, open a C# solution (ex. a extension solution)
2. open a cs file.

### Current behavior
VS crash

**Comment by danielscherzer** [comment]
I assume you have disabled the extension and repeated the process and no crash has occurred?

**Comment by lancelot-coder-chen** [comment]
Yes.

**Comment by robotjatek** [comment]
Hi,
I don't know if this is the same error that I have or not, but I think I have the same or similar issue. For me it does not crash Visual Studio but I get a couple of error messages. I'm on the `16.4.0 Preview 6` version. It was working flawlessly for some time. The problems started a couple of VS updates before. When this extension is enabled I get a `Could not find the Microsoft.VisualC.CppClassifierProvider. Installing the C++ Visual Studio aspect should help.` error message uppon opening a file in a solution. See: ![1](https://user-images.githubusercontent.com/5225221/69425099-8fc41000-0d2a-11ea-93eb-8b90a7b63c92.PNG)

After the solution has opened I get an error message about a `NullReferenceException`: ![3](https://user-images.githubusercontent.com/5225221/69425145-abc7b180-0d2a-11ea-9352-5a050fdefc5d.PNG) 

Also the syntax highlight has stopped working in the GLSL files.
Disabling the extension makes the error messages go away.

Attached ActivityLog.xml: 
[ActivityLog.zip](https://github.com/danielscherzer/GLSL/files/3879452/ActivityLog.zip)

**Comment by danielscherzer** [comment]
This issue is maybe related to #43

**Comment by danielscherzer** [comment]
I did an update of the extension. Maybe this issue is now resolved.

**Comment by lancelot-coder-chen** [comment]
It is. The new version extension fix the issue. Thanks.
