### ISSUE TITLE
Unexpected error highlights with gl_VertexIndex and gl_InstanceIndex

### ISSUE THREAD

**Issue by ltqsoft** [danielscherzer/GLSL#45]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 0.6.78

### Description
gl_VertexIndex and gl_InstanceIndex highlighted as errors.

### Steps to recreate
Type these:
gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);
gl_Position = vec4(positions[gl_InstanceIndex], 0.0, 1.0);

### Current behavior
Error #143 with gl_VertexIndex and gl_InstanceIndex
Error #166 with operator[]
These are not errors, the SPIR-V can still be generated successfully.

### Expected behavior
The extension should recognize these expressions and not highlight them as errors.

**Comment by danielscherzer** [comment]
These errors come from the OpenGL shader compiler of either your graphics card driver or from the external compiler you set in the options.
Do you use an external compiler? What shader type do you use vertex?
For glslang as external compiler you could use the -G option, which works for me for Vulkan code.
Cheers, Daniel

**Comment by ltqsoft** [comment]
gl_VertexIndex and gl_InstanceIndex are in vertex shader scope, so certainly it's vertex shader. I haven't checked with gl_VertexID and gl_InstanceID yet, so I don't know if those also have this issue.
I tried renaming the file to shader.vert and shader.frag, still the extension throws those errors onto Visual Studio.
It looks like the extension doesn't have any custom configuration, thus I assume that this issue comes from the extension itself, not the compiler.

**Comment by danielscherzer** [comment]
If you do not set an external compiler via the options (see below) the extension tries to compile via the OpenGL driver. I recommend an external compiler and the the -G option for Vulkan.

Regarding the options of the extensions please look at 
https://github.com/danielscherzer/GLSL/blob/master/README.md
under #Configuration.

**Comment by ltqsoft** [comment]
Sorry I misunderstood the term "options" mentioned above, and I thought that extension configurations should be somewhere else.
The -G option didn't work for me, however the -V was fine.

**Comment by danielscherzer** [comment]
Does the -V option not work for you?
