### ISSUE TITLE
After update to VS 16.4 get: System.NullReferenceException

### ISSUE THREAD

**Issue by BrutPitt** [danielscherzer/GLSL#46]
### Installed product versions
- Microsoft Visual Studio 2019 version: 16.0.29519.181 (16.4)
- GLSL version 0.6.78 (10/22/2019) 

### Description
**Visual Studio error**, and this is the log of single error:
System.NullReferenceException: Object reference not set to an instance of an object.   at DMS.GLSL.TodoClassification.TodoTagger.<Microsoft-VisualStudio-Text-Tagging-ITagger<DMS-GLSL-TodoClassification-TodoTag>-GetTags>d__6.MoveNext() in C:\projects\glsl\src\TodoClassification\TodoTagger.cs:line 57   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()

### Steps to recreate
Open solution with glsl opened, or load a glsl file

### Current behavior
After update form 16.3.10 -> 16.4 (update succesfull, without any problem)
When load solution with glsl file loaded in the editor, appear following dialog box:
![error](https://user-images.githubusercontent.com/16171743/70099271-aaea2600-162e-11ea-8a72-b5181d329ee8.jpg)
Several times (3 times for any glsl file opened in solution), below a partial log (if can help)
![error2](https://user-images.githubusercontent.com/16171743/70100863-7c227e80-1633-11ea-9fc6-85cdc82b672b.jpg)

And same thing if load a glsl file, or switch to a glsl file
Of course (but I write to avoid doubts) after the syntax highlighting disappear from glsl files, and disabling the extension there are no errors in VS.
And equally obviously, any C++ component is installed (despite the dialog box)

### Expected behavior
Before update, with VS 16.3.10, everything worked well

**Comment by danielscherzer** [comment]
I think this issue is related to issue #43 and the new version 0.7.80 should fix this.

**Comment by BrutPitt** [comment]
Yes, thank you: the 7.80 resolves the issue!

My mistake:  I did not look into the closed issues, or even if there was a new release here, on github.

Thanks again.
