### ISSUE TITLE
More file extensions support

### ISSUE THREAD

**Issue by juhl** [danielscherzer/GLSL#5]
How can I add file extensions to be highlighted in GLSL ?

**Comment by danielscherzer** [comment]
A quick solution is:
In `ContentTypeGlsl.cs` there is an entry for each registered file extension of the form
```
[Export]
[FileExtension(".vert")]
[ContentType("glslVertexShader")]
private static FileExtensionToContentTypeDefinition vertFileType;
```
Copy the 4 lines and change the attribute `[FileExtension(".vert")]` to your file extension and rename the `vertFileType` variable to some name. Compile and install your altered glsl.vsix. I will think about how to register a new file extension without changing the code. If you have any ideas, I would be happy to hear them.
