### ISSUE TITLE
GLSL extension currently crashes Visual Studio 2019 Community Preview

### ISSUE THREAD

**Issue by Andy608** [danielscherzer/GLSL#50]
### Installed product versions
- Visual Studio: 2019 Community Preview
- This extension: 0.7.88

### Description
I recently downloaded the new [Visual Studio Community Preview](https://visualstudio.microsoft.com/vs/preview/). When I install this extension, the log comes back saying it installed successfully, but when I open my CMake project and click anywhere in the editor, Visual Studio closes immediately without warning. When this extension isn't installed, everything works normally.

### Steps to recreate
1. Download the [Visual Studio Community Preview]((https://visualstudio.microsoft.com/vs/preview/))
2. Open Visual Studio and open a CMake project.
3. Click anywhere in the editor and Visual Studio should quit right away.

### Current behavior
Visual Studio crashes on mouse click.

### Expected behavior
Visual Studio should just work as it does normally.

Here is the install log in case it provides any helpful details about the issue.[dd_VSIXInstaller_20200112155942_2168.log](https://github.com/danielscherzer/GLSL/files/4051431/dd_VSIXInstaller_20200112155942_2168.log)

I really like using this extension and needed to upgrade to Visual Studio Preview because of a bug with CMake projects in the current Visual Studio version. It would be great if I could continue using this extension in the preview as well.

Thanks!

**Comment by Andy608** [comment]
I was able to get to the extensions tab after installing and it gave me the option to enable the plugin. Once I enabled the plugin everything seems to be working fine. Still maybe something to look into though. Strange, but I'm glad it works now!

**Comment by danielscherzer** [comment]
Thanks for the log! The installer thinks you have 3 versions of Visual Studio installed:
```
1/12/2020 3:59:48 PM - Found installed product - Visual Studio Community 2019 Preview
1/12/2020 3:59:48 PM - The extension with ID 'b62242eb-0ae5-4494-b013-6158ade63816' is not installed to Visual Studio Community 2019 Preview.
1/12/2020 3:59:48 PM - Found installed product - Visual Studio Community 2017
1/12/2020 3:59:48 PM - The extension will be upgraded from version 0.6.78.
1/12/2020 3:59:48 PM - Found installed product - Visual Studio Community 2019
1/12/2020 3:59:48 PM - The extension will be upgraded from version 0.7.84.
...
1/12/2020 4:00:26 PM - Install to Visual Studio Community 2019 Preview completed successfully. The extension has been installed to C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\D0UYL1K0.0E0\
```
The installer did two upgrades and one installation, but I see no errors. It is also strange that you needed to enable the extension.... I do not know what went wrong here. 

Cheers,
Daniel

**Comment by danielscherzer** [comment]
I did a cleanup, wich may resolve your issue.

**Comment by danielscherzer** [comment]
I will close this issue because no further reports have come in and I did some updates inbetween. Please feel free to reopen it if the problem persists.
