### ISSUE TITLE
Sometimes, the extension prevents me from saving files

### ISSUE THREAD

**Issue by stiffsen** [danielscherzer/GLSL#54]
### Installed product versions
- Visual Studio: 2017 Professional 15.9.21
- This extension: 0.7.96

### Description
Sometimes (happens very rarely), this extension prevents me from saving any files. I press ctrl+s or click File>Save and nothing happens. When I then close Visual Studio, Studio asks me to save the file, which I confirm, but the file still wouldn't save. The only thing that helped, was to temporarily disable the GLSL extension, save and then enable it again.

### Steps to recreate
I cannot reliably reproduce this issue, but it might be correlated to reporting shader-compilation-errors. If I recon correctly, the issue only appeared after a shader compilation error had occured.

**Comment by danielscherzer** [comment]
Thanks for the feedback! I must confess I do not really know what could be the cause of this behavior. I never had this issue, but I will keep my eyes open.

**Comment by dicalexon** [comment]
It happens for me too, quite often. Cannot describe way to reproduce though. It happens randomly.

**Comment by danielscherzer** [comment]
Is this still an issue?

**Comment by stiffsen** [comment]
I am not actively working with GLSL anymore, so I uninstalled the extension, sorry daniel.
