### ISSUE TITLE
Compiler Error 

### ISSUE THREAD

**Issue by SianSallway** [danielscherzer/GLSL#56]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 0.7.98

### Description
Here is the code where the compile error occurs in the hlsl and hlsli files.

### Steps to recreate
1. Set the GraphicsProject_SS project to startup project.
2. All the code to run the project and present the issue should be in the project files I have include here:

https://drive.google.com/drive/folders/1In5L8A7VxccxdzWSjxdUtnKX_JMmPXZC?usp=sharing

### Current behavior
In this .hlsli and hlsl files containing code for a vertex and fragment shader, I keep getting a compile error when using the glsl 'in' and 'out' keywords. This error is - syntax error: expected token 'in'. I can't find a reason for this to be occurring or how to fix it.

### Expected behavior
This file should have no errors, the vertex and fragment shader files should compile.

**Comment by danielscherzer** [comment]
I assume the errors are in the normalmapFrag|Vert.txt? The extension shows no errors for these files. Are you talking of compilation errors when compiling the shaders in your project?

**Comment by SianSallway** [comment]
Hi Daniel,
The error takes place when I try to compile the Header.hlsli
an VertexShader.hlsl files, these files contain the same code in
the .txt files. If I remove the .hlsl and .hlsli files from the project I
don't get this error.

**Comment by danielscherzer** [comment]
As I understand it, your compilation errors have nothing to do with the extension, but with your application code. Many things could be responsible for you errors for instance your graphics card drivers. Regardless, this is an issue page for the extension and as such this is the wrong forum to address an issue that has nothing to do with the extension. I would recommand posting a question on stackoverflow.
