### ISSUE TITLE
[FEATURE REQUEST]: Copy current solution's/project's include directories and add to glslangValidator as arguments

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [danielscherzer/GLSL#58]
### Installed product versions
2019 Community Edition

### Description
I have a complex project with huge GLSL shaders that use `#include` to hook themselves in, everything works nicely if I use `glslangValidator` from the latest Vulkan SDK (the old `glslangValidator` you bundle with your extension doesn't seem to support `GL_GOOGLE_include_directive`, although I havent tried it with the `-V` option).

However I need to pass a `-I /path/to/where/I/keep/my/shaders` as an extra argument, which is obviously nice and easy... but this is a global option for the extension for the whole IDE.

This gets tricky if you're working on two different branches with two different shader versions, I'd pretty much have to manually change that option every single time I switch projects/branches.

### Wanted behavior
Please parse my `.sln` or `.vcxproj` compiler options and just use the include directories for C/C++ or whatever language I'm using for the current active project.

**Comment by danielscherzer** [comment]
If I understand you correctly you use the `Arguments for the external compiler executable` option to set your include path.
Would you be happy if I would expand variables, like `-I $(Include_Dir)/shaders`, for this option. This should make your proposed workflow possible.

**Comment by devshgraphicsprogramming** [comment]
> Would you be happy if I would expand environment variables, like in -I %My_Shader_Dir%, for this option. This should make your proposed workflow possible if you set the environment variable %My_Shader_Dir% when switching your project/branch.

Yeah I actually tried something like `-I$(SolutionDir)../include` but obvs it didnt work ;)

The worse part is that the "Print to Output" option doesn't work, I can't see what you've invoked the external compiler with and what was the result.

Another problem I have is that I can't use `glslangValidator`, well because its a validator and not a compiler, to handle includes and the plethora of extensions its actually the `glslc` binary that is needed... however it seems you seem not to be able to parse its output.

I did some dry tests with `--target-env=vulkan1.1 -IC:\work\IrrlichtBAW\branch\include` as arguments and the `glslc.exe` from my Vulkan SDK and in the command line I get errors without a problem, but your extension no longer reports anything.

**Comment by devshgraphicsprogramming** [comment]
@danielscherzer now there remains the other issue that your extension has been targeting parsing `glslangValidator` output not `glslc` and `glslangValidator` doesn't really seem to honor `-I`, `-V` nor make any assumptions about the shader's stage
