### ISSUE TITLE
Logical XOR breaks syntax highlighting

### ISSUE THREAD

**Issue by Ext3h** [danielscherzer/GLSL#60]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: since 0.7

### Description
Logical XOR operator `^^`  breaks syntax highlight until end of file.

![grafik](https://user-images.githubusercontent.com/7760870/83891185-14b5ca80-a74d-11ea-8aa6-f2bf91678015.png)

Looks like `^` was forgotten in `Lexer<TokenClassificationType>.ParserOperator `.

**Comment by danielscherzer** [comment]
Thanks for reporting this bug! I published a new version that should fix this.

**Comment by Ext3h** [comment]
Thanks, works fine now.
