### ISSUE TITLE
Syntax highlighting no longer working

### ISSUE THREAD

**Issue by simileV** [danielscherzer/GLSL#61]
### Installed product versions
- Visual Studio: [2019 community]
- This extension: [0.8.102]

### Description
Syntax highlighting no longer working, will occasionally work on select files. Extension is *.glsl

### Steps to recreate
1. open a *.glsl file

### Current behavior
displays plaintext instead of syntax highlighting

### Expected behavior
syntax highlighting

**Comment by danielscherzer** [comment]
Could you provide me with the shortest code of a shader that breaks syntax highlighting.

**Comment by simileV** [comment]
```
#version 440 core

layout(location = 0) in vec3 pE;

void main()
{
	gl_Position = vec4(pE, 1.f);
}
```

If I comment out the `#version 440 core` the syntax highlighting shows, but the shader does not work. Another file **works** with syntax highlighting with this:
```
#version 440 core

in Vert
{
    vec2 uv;
    vec3 T_VS, N_VS, N_VS_ssao, P_WS, P_VS;
} v;

layout(location = 0) out vec4 gBuf0;
layout(location = 1) out vec4 gBuf1;

void main()
{
	gBuf0 = vec4(v.N_VS, gl_FrontFacing);
	gBuf1 = vec4(v.P_VS, 1.f);
}
```

**Comment by danielscherzer** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/8530595/84048421-0e715980-a9ac-11ea-87ca-dc673168fe87.png)

...works for my setup, which makes it hard to debug....

**Comment by simileV** [comment]
I found the issue which was that the line endings that dont work are LF and the ones that do work are CRLF. Does your plugin only work for CRLF?

**Comment by danielscherzer** [comment]
Thanks for finding this bug! Now the plugin should work for CRLF and LF style line endings.
