### ISSUE TITLE
custom colors for user key functions

### ISSUE THREAD

**Issue by barnes14** [danielscherzer/GLSL#62]
Hi
Some time ago, you added by my request custom colors for user key words. It's nice feature. You can add a similar thing for custom functions (so that the user's functions and his words have different colors.)
For example, 'texture2DRect' is a user function, but 'location' is a word. But they are marked in one color, this is not a strong problem, but if you add several blocks of custom colors this would be great

**Comment by barnes14** [comment]
No, I’m talking about two user lists, each of which has its own color highlight.
I also tried adding the source code to my function names and words, but that didn't work. I added new glsl names in glslFunctions.txt and glslKeywords.txt.

**Comment by danielscherzer** [comment]
Changing glslFunctions.txt and glslKeywords.txt: You would have to recompile and install this changed version of the extension, but I can add a second user list with a distinct user defined color.

**Comment by barnes14** [comment]
Ok.

**Comment by danielscherzer** [comment]
Does it now work as expected?

**Comment by barnes14** [comment]
yea)
