### ISSUE TITLE
Extension Throws "CompositionFailedException" on Initialization (opening .vert for the first time) in Visual Studio 2019

### ISSUE THREAD

**Issue by Sage-King** [danielscherzer/GLSL#65]
### Installed product versions
- Visual Studio: 2019
- This extension: Not sure, latest as of 7/5/2020 (from vs marketplace)

### Description
Opening my .vert file in Visual Studio 2019 pops up "An exception of type CompositionFailedException has been encountered, This may be caused by an extension."  

### Steps to recreate
1. Install the extension from .vsix provided from the Visual Studio marketplace
2. Open .vert file in Visual Studio 2019

### Current behavior
It's popping up an exception and not doing anything promised in the readme.

### Expected behavior
All of the stuff promised in the readme. 

[ActivityLog.zip](https://github.com/danielscherzer/GLSL/files/4875335/ActivityLog.zip)

**Comment by danielscherzer** [comment]
Thanks for the activity log! This helped to narrow it down. Does the new version work for you?

**Comment by Sage-King** [comment]
Ay you're kinda a dick aren't you.

**Comment by Sage-King** [comment]
I'm sorry for my last comment, this commit seems to have fixed the problem.  I just thought you were sassing me because all I saw when I checked the commit was a changed changelog.  I'm sorry, I feel bad now. :(

**Comment by danielscherzer** [comment]
no worries!
