### ISSUE TITLE
Adding "layout(early_fragment_tests) in" forces shader type to Tesselation Evaluation

### ISSUE THREAD

**Issue by Sixshaman** [danielscherzer/GLSL#68]
### Installed product versions
- Visual Studio: Community 2019
- This extension: 0.10.111

### Description
Forcing early-z tests by adding `layout(early_fragment_tests) in` in the beginning of a fragment shader changes the shader type from Fragment to Tesselation Evaluation.

### Steps to recreate
Write a Test.glsl file like this:
```
#version 430 core

layout(early_fragment_tests) in;

out vec4 fragColor;

void main()
{
	fragColor = vec4(1.0f);
}
```

### Current behavior
The line `layout(early_fragment_tests) in` is marked as an error. Any fragment shader-specific variables, like `gl_FragCoord`, are marked as undefined. Commenting out the `layout(early_fragment_tests) in` line fixes the problem.

### Expected behavior
Shader type should be correctly recognized as Fragment.

**Comment by danielscherzer** [comment]
Sorry for the delay I was on holidays.

**Comment by danielscherzer** [comment]
Does it work now as expected?

**Comment by Sixshaman** [comment]
> 
> 
> Does it work now as expected?

Yes! Thank you for fixing.
