### ISSUE TITLE
Pasting In Shader Code Crashes VS2017

### ISSUE THREAD

**Issue by codeacula** [danielscherzer/GLSL#7]
### Installed product versions
- Visual Studio: 2017 Community 15.6.6
- This extension: 0.2

### Description
Pasting hlsl code into Visual Studio causes Visual Studio to crash. Uninstalling extension resolves problem.

### Steps to recreate
1. Create a shader file (in this case, `container.fs.glsl`) in Visual Studio
2. Paste in copied glsl code (in this case, from the following location: https://learnopengl.com/Lighting/Colors)
3. Visual Studio crashes.

### Current behavior
Crashes Visual Studio 2017

### Expected behavior
Paste copied glsl code from clipboard into opened file

**Comment by danielscherzer** [comment]
hi,

thanks for your feedback! I could not reproduce this error.
I did the following:
1.     Create a shader file (in this case, container.fs.glsl) in Visual Studio
2.     Paste in copied glsl code (in this case, from the following location: https://learnopengl.com/Lighting/Colors). I pasted: `
#version 330 core
layout (location = 0) in vec3 aPos;

uniform mat4 model;
uniform mat4 view;
uniform mat4 projection;

void main()
{
    gl_Position = projection * view * model * vec4(aPos, 1.0);
} `
3.     Visual Studio still works and shows the shader with syntax coloring.
