### ISSUE TITLE
using EnvVars in external compiler path

### ISSUE THREAD

**Issue by spfuetzner** [danielscherzer/GLSL#71]
It would be nice if you could use environment variables in the file path of the external compiler.

The external compiler is often used to support the Vulkan and Google include extensions and the required glslangValidator is usually installed with the LunarG Vulkan SDK. Unfortunately, the version number is in the path, so the option in the GLSL extension has to be adjusted with every update.

Possible spellings could be $(EnvVar) or %EnvVar%:

    $(VULKAN_SDK)\Bin\glslangValidator.exe

    %VULKAN_SDK%\Bin\glslangValidator.exe

**Comment by danielscherzer** [comment]
Hopefully this works as expected...

**Comment by spfuetzner** [comment]
I'm afraid not. The following is now in the log:

    [09.30 11:23:16.197] Using external compiler 'C:\VulkanSDK\1.2.148.1\Bin\glslangValidator.exe' with arguments '-C -r -w --target-env vulkan1.1 --target-env vulkan1.2' on temporal shader file 'C:\Users\kiba\AppData\Local\Temp\shader.frag' 
    [09.30 11:23:26.204] External compiler did take more than 10 seconds to finish. Aborting! 
    [09.30 11:23:26.236] Dumping shader log:
    Usage: glslangValidator [option]... [file]...

    'file' can end in .<stage> for auto-stage classification, where <stage> is:
        .conf   to provide a config file that replaces the default configuration
                (see -c option below for generating a template)
        .vert   for a vertex shader

This is followed by the complete description as it is displayed when glslangValidator is started without parameters.

**Comment by danielscherzer** [comment]
Thanks for the quick reply. Too many quotes...

**Comment by spfuetzner** [comment]
Fixed! Also using environment variables now works. Thank you!

One small problem is still left. In the "Message" tab of the Error List window there is always one message:

    Could not parse line 'C:\Users\kiba\AppData\Local\Temp\shader.frag'

The log has no such warning.

**Comment by danielscherzer** [comment]
Even if there is no error in the code?

**Comment by spfuetzner** [comment]
Only with the external glslangValidator compiler, but then even for the simplest shader:

    #version 460
    void main() {}

It prints the message for line 1 in my shader. But it's not a big problem, most of the time informational messages are disabled anyway in the Error list.

**Comment by danielscherzer** [comment]
Currently my parser handles each line individually, which makes him simple (modeless) and robust in terms of additional lines without usable error information, like preambles or stats at the end. If I start to filter lines I think the parsing will become more error prone to changes in the shader compiler outputs. So I would argue for keeping the status quo.

**Comment by danielscherzer** [comment]
Can I close this issue?

**Comment by spfuetzner** [comment]
> 
> 
> Can I close this issue?

Sure. And thanks!

**Comment by danielscherzer** [comment]
Thanks!
