### ISSUE TITLE
Suggestion: Make user keyword's coloring take precedence over builtins.

### ISSUE THREAD

**Issue by gamagan** [danielscherzer/GLSL#72]
Make user keywords1/2 coloring schemes take precedence over the builtin-functions, builtin-keywords coloring, in case the user wants to override specific kewords/builtin colors.

In my particular usecase, there are a few keywords that I would like to stand out in the syntax highlighting, but they are shown as blue and can't be changed individually.

Thanks

**Comment by danielscherzer** [comment]
Thanks for your feedback! This suggestion is included in the new release. Does it work as expected?

**Comment by gamagan** [comment]
Just tested it and it's working perfectly. You're amazing! 

Thanks a million for this extension, and thank you for making the update.

**Comment by danielscherzer** [comment]
Excellent! I will close the issue...
