### ISSUE TITLE
Syntax Error not reported on erroneously calls of internal variables of Uniform Blocks

### ISSUE THREAD

**Issue by Ragnarox97** [danielscherzer/GLSL#74]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 0.10.120

### Description
It does not report a syntax error within a .frag file

### Steps to recreate
1. Create a .frag file
2. Create a Uniform Block (I created it with the std140 layout) called, for example, exampleBlock. Insert inside the variables (I 
    have inserted 4 vec4)
3. Create a basic main and use within it the variables defined inside the Uniform Block, so that these variables are called up, 
    erroneously, using "Uniform Block name"."variable name". In our case: exampleBlock.firstVec

### Current behavior
The extension does not recognize this syntax as an error, when it is. As a consequence of this, other subsequent errors, of any kind, are not reported. I could write: colorVector.rgbgbrrgbfhskwiw ....., where colorVector is a vec3, and it would not be reported as an error.

### Expected behavior
The extension must recognize the syntax: exampleBlock.variableName, as an error, where exampleBlock is the name of the Uniform Block and variableName is the name of a variable within the Uniform Block

![1](https://user-images.githubusercontent.com/74871201/99910527-d27a4880-2cee-11eb-90a3-1e3d3a883291.JPG)
![2](https://user-images.githubusercontent.com/74871201/99910528-d60dcf80-2cee-11eb-961d-c8ce3466b248.JPG)

**Comment by danielscherzer** [comment]
Thanks for your feedback! The extension does not do the error checking, but either the OpenGL driver or if specified in the options an external compiler is used. These either generate errors (like the stricter glsllang) or are too forgiving (like some NVIDIA drivers).

My NVIDIA driver seems to handle the situation correctly:
![grafik](https://user-images.githubusercontent.com/8530595/99916965-be920f00-2d0d-11eb-8633-78495d84ae12.png)
Does my simplified version of your example produce the same problems as your longer example for you?

**Comment by Ragnarox97** [comment]
I replicated your example and the result is the same. At this point then, I'm sure it's because of my video card drivers. I have an HP Pavilion dv6 that is equipped with a Radeon HD 7690M XT. The pc is almost 10 years old and the drivers probably can't handle this situation.

![Cattura](https://user-images.githubusercontent.com/74871201/99975585-b7691080-2da2-11eb-9efc-d4566d249528.JPG)

So I'll have to be more careful when I write, at least until I get a new pc. 
Thanks anyway for your assistance :)

**Comment by danielscherzer** [comment]
No problem! You could try and install the latest drivers from the radion homepage and not from HP, even if they are regarded as incompatible. Sometimes this works, sometimes it wrecks your system. So be sure to make a system backup beforehand.
