### ISSUE TITLE
Syntax highlighting breaks after defining a multi-line macro

### ISSUE THREAD

**Issue by ameerj** [danielscherzer/GLSL#75]
### Installed product versions
- Visual Studio: 2019
- This extension: 0.10.120

### Description
Defining a multi-line macro breaks the highlighting after the second line of the macro definition. Syntax highlighting is then broken for the rest of the shader.

### Steps to recreate
Define a multi-line macro. for example:
```glsl
#define READ_UINT_VALUES(N)                    \
    uint v[N];                                 \
    for (uint i = 0; i < N; i++) {             \
        v[i] = color_values[colvals_index++];  \
    }
```

### Current behavior
Syntax highlighting breaks after defining the multi line macro, with the only workaround being a single-line macro definition.

### Expected behavior
Syntax highlighting should not break in this case. The backslash `\` character should escape the newline and highlight the multi-line macro as if it were a single line macro.

**Comment by danielscherzer** [comment]
Thanks for your feedback! I published a new version, which hopefully resolves this issue.

**Comment by ameerj** [comment]
Indeed the issue is resolved with the new version. Thanks for the prompt fix!
