### ISSUE TITLE
Example MSVC project

### ISSUE THREAD

**Issue by jjYBdx4IL** [danielscherzer/GLSL#80]
Would be great if you could provide an example MSVC project where this extension is known to work. I have installed it and nothing happens to my .frag and .vert files when I open them in the editor, all augmented with red underlines, which suggests the syntax highlighting is not activated for those files.

**Comment by danielscherzer** [comment]
You do not need a solution. You can also load a single file and the extension should work.
For example:
![Screenshot (5)](https://user-images.githubusercontent.com/8530595/112935616-65574380-9124-11eb-81e7-e7ea314c9b1b.png)
Do you have nsight installed? This extension is known to interfere with well known shader extensions. But you can redefine the used extensions in the option settings (see readme on github)

**Comment by jjYBdx4IL** [comment]
Inside my solution it works with newly created .glsl files. However, it's not working as soon as I define a Custom Build Tool for those files.

**Comment by jjYBdx4IL** [comment]
I disable all the other extensions. Now it's working.

**Comment by danielscherzer** [comment]
Yes, I contacted the author a year ago, but I got no response. Sorry!

**Comment by jjYBdx4IL** [comment]
np. thx for your effort!
