### ISSUE TITLE
Editing multiple lines causes NullReferenceException to be thrown

### ISSUE THREAD

**Issue by NRUB** [danielscherzer/GLSL#81]
### Installed product versions
- Visual Studio 2019 Community
- This extension: version 0.10.124

### Description
When editing more than one line at a time with multiline editing, VS is throwing NullReferenceException. Although the exception is being caught by Visual Studio and doesn't cause hard crash, it is being forwarded and the appropriate information is being displayed in that slim light yellow bar above editor. My best guess it has something to do with IntelliSense, but unfortunately in my case "Open log file" button does nothing. This problem will appear only once, during any given session. To reproduce it after the message is dismissed it is required to restart Visual Studio, to have it happen again.

### Steps to recreate
1. Open Visual Studio
2. Create empty GLSL shader file
3. Add few new lines
4. Hold Alt and select 2-3 lines
5. Type anything (e.g. "aaa")
6. Wait a second and exception should be thrown
7. If nothing happens, restart Visual Studio and repeat steps 4 to 6.

Here is a screenshot of the message in context of a test file, in new empty project.
![exception](https://user-images.githubusercontent.com/16063403/115286755-b8368080-a14f-11eb-81cb-ccd5a565bfde.png)

**Comment by danielscherzer** [comment]
Does version 0.10.125 now work as expected?

**Comment by danielscherzer** [comment]
Can we close this issue?
