### ISSUE TITLE
How can I compile my shader using the extension?

### ISSUE THREAD

**Issue by mrjbom** [danielscherzer/GLSL#82]
### Installed product versions
- Visual Studio: 2019 Professional 
- This extension: 0.10.124

### Description
How can I compile my shaders? I absolutely do not observe such a possibility. How should I get the extension to do this?
In the extension settings, I specified the path to glslc.exe and the argument is "-c"

**Comment by danielscherzer** [comment]
Shader compilation is used by the extension internally to highlight syntax errors in your shader code. As a default a separate OpenGL thread that compiles the shader on the primary graphics card is used. You can also select an external compiler executable to use for this purpose in the options menu. 

If I have understood you correctly you have specified an external compiler. Does the error tagging (error squiggles) work correctly when you do not specify an external compiler?

**Comment by mrjbom** [comment]
I am facing such a problem:
![image](https://user-images.githubusercontent.com/37502620/115773022-7b20f700-a3b8-11eb-9e3a-16e05c4b1d0e.png)

I have set the following settings:
![image](https://user-images.githubusercontent.com/37502620/115773126-9b50b600-a3b8-11eb-9622-544e9137803a.png)

When I compile shaders, I don't get any errors or warnings.
![image](https://user-images.githubusercontent.com/37502620/115773492-0ef2c300-a3b9-11eb-802c-7dfc132160d5.png)

**Comment by danielscherzer** [comment]
Did you also try to use the External compiler executable file path field?

**Comment by mrjbom** [comment]
Oops, I didn't notice this field, I expected the arguments and the compiler path to be specified together.
Thank you for your help!

**Comment by danielscherzer** [comment]
Thanks for clearing this up!
