### ISSUE TITLE
Bad keybind interaction with other extensions

### ISSUE THREAD

**Issue by ror3d** [danielscherzer/GLSL#85]
### Installed product versions
- Visual Studio: Community 2019 Version 16.10.1
- This extension: 0.10.125
- vsvim https://github.com/VsVim/VsVim

### Description
When using the extension and an auto-complete popup appears, pressing Esc with using VsVim should close the popup AND put VsVim to normal-mode. What happens instead is that only the popup is closed.

### Steps to recreate
1. Open a shader file
2. Start writing the name of an existing variable inside a function
3. press Esc to close the popup and leave VsVim's insert-mode.

### Current behavior
The popup is closed but insert-mode is still active, instead of being in normal-mode.

### Expected behavior
The popup should be closed and VsVim should be in normal-mode.

---

In any other language server, when in insert-mode in VsVim, pressing Esc when an auto-complete popup is open closes the popup and leaves insert-mode.

I suspect for some reason the extension is capturing the key event and not letting it bubble up through other extensions.

**Comment by danielscherzer** [comment]
Thanks for your feedback! I created a new version of the extension 0.10.131, which hopefully resolves this issue.

**Comment by ror3d** [comment]
Seems to work as expected now, thank you very much!
