### ISSUE TITLE
The OptionsPagePackage package did not load correctly.

### ISSUE THREAD

**Issue by zihaoliu22** [danielscherzer/GLSL#89]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 0.10.131
- on Latest Windows 10 environment.

### Description
I recently updated the extension from 0.10.125 to 0.10.131. Then I got the following errors when I try to edit the GLSL configuration:

![image](https://user-images.githubusercontent.com/88647522/128666169-26ad82fc-8e3f-4105-b679-000f4734853f.png)

The activity monitor xml file shows:

![image](https://user-images.githubusercontent.com/88647522/128666271-83e6a675-a979-4092-852f-3167bd7add34.png)

Any idea of how to address this issue, or if there is a compiled older version of GLSL language extension (0.10.125) that I could download, would be appreciated. 

### Steps to recreate
1. download Visual Studio 2017 Professional
2. Install the latest GLSL language extension from visual studio marketplace.
3. Go to tools and then GLSL Language Extension.
4. The error should show up.

### Current behavior
the extension does not run in the Visual Studio environment I had locally. I attached error message.

### Expected behavior
The latest extension should work as expected in the Visual Studio Professional 2017.

**Comment by danielscherzer** [comment]
Version 0.10.125 of the extension did work, but 0.10.131 does not work for you? Is this correct?

**Comment by zihaoliu22** [comment]
thanks for the response. Version 0.10.125 did work, but 0.10.131 does not work on my visual studio 2017. correct.

I currently only have the visual studio 2017 Professional. Is it possible for me to download the 0.10.125 version instead?

**Comment by danielscherzer** [comment]
Thanks for the information. We currently think if we keep VS17 support or drop it. So possibly a future version will again work on vs17.

Yes the version is available on github: https://github.com/danielscherzer/GLSL/releases/tag/0.10.125

**Comment by zihaoliu22** [comment]
I got the 0.10.125 to work on the visual studio 2017. Thanks.
