### ISSUE TITLE
Instant crash when opening this geometry shader

### ISSUE THREAD

**Issue by AHUMANTHATISHUMAN** [danielscherzer/GLSL#9]
### Installed product versions
- Visual Studio: Visual Studio Community 2017
- This extension

### Description
When opening a particular geometry shader, Visual Studio instantly crashes with the error: System.AccessViolationException (Trying to read protected data).

### Steps to recreate
1. open this file: https://www.dropbox.com/s/4venwdszb7qn6we/shape.geom?dl=0

### Current behavior
Visual studio crashes. It did not crash during the creation of the file

### Expected behavior
It should be working as normal.

**Comment by danielscherzer** [comment]
Interesting OpenGL shader compiler error! 
Even this one line geometry shader  
> void main() { gl_Position = vertex0+vec4(gl_in.gl_Position[0]); }
kills the compiler. 
I now catch this exception and give an error message and squiggle.
I was able to continue editing the shader afterwards, but this is a serious exception, which could kill the whole OpenGL context in a different driver version.

**Comment by AHUMANTHATISHUMAN** [comment]
Thanks!
It all works correctly now and I can fix the silly mistake in the shader!
