### ISSUE TITLE
Suggestion: Support for Vulkan built in variables

### ISSUE THREAD

**Issue by cambo14** [danielscherzer/GLSL#90]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 0.10.131

### Description
It would be very useful to add support for built in variables for Vulkan. While it seems to be partly implemented (the built in variables show up in the auto-complete dropdown). It still gives errors when you add it to your code

### Steps to recreate
create an object using an inbuilt variable for Vulkan, for example:
`vec4(positions[gl_VertexIndex], 0.0, 1.0);`

### Current behavior
the inbuilt variable shows up in the autocomplete menu however once it is entered the line has the error `gl_VertexIndex' : undeclared identifier`

### Expected behavior
no error is created after using built in variables for Vulkan

**Comment by danielscherzer** [comment]
From the readme
"Note that support for Vulkan shader types is currently only provided via an external compiler (like glslangValidator)."
So put in the path to your compiler and parameters in the extension options dialog and it should work.
Hope this helps.

**Comment by danielscherzer** [comment]
Can I close this issue?
