### ISSUE TITLE
Can this work without the .glsl filename extension?

### ISSUE THREAD

**Issue by patrikpatrik** [danielscherzer/GLSL#94]
### Installed product versions
- Visual Studio 2022 Community
- This extension: 0.11.154

### Description
For some reason it only recognizes the 1st shader filename is: shader
My second one is shader2 but doesn't recognize that.

**Comment by danielscherzer** [comment]
Visual Studio requires me to register my extension to certain file extensions. So it will notwork without any file extension.

**Comment by patrikpatrik** [comment]
Oh okay gotchya. Thank you for the quick response!
