### ISSUE TITLE
VSCode release

### ISSUE THREAD

**Issue by chickenSandwich** [danielscherzer/GLSL#95]
Is there any chance you could target VSCode?

**Comment by danielscherzer** [comment]
I have looked into this becvause I was not happy with the available extensions for GLSL in VS Code. Regrettably, VS Code extensions seem to be a completely different thing: They have to be coded in typescript and everything works differently. So in essency I would have to make a new extension...

**Comment by chickenSandwich** [comment]
Thanks for letting me know.
